---

# Notes -
# The following 'error' is 'rescued' and then corrected
# TASK [nvidia.nvidia_driver : attempt to install kernel support packages for current version] ***********************************************************************************************************************************************
# fatal: [10.10.1.130]: FAILED! => {"changed": false, "msg": "No package matching 'kernel-headers-3.10.0-1127.el7.x86_64' found available, installed or updated", "rc": 126, "results": ["No package matching 'kernel-headers-3.10.0-1127.el7.x86_64' found available, installed or updated"]}

- name: Base Docker installation for all
  hosts: all
  any_errors_fatal: true
  become: true
  gather_facts: true
  tasks:
    - name: Disable firewall rules (Debian)
      become: true
      ufw:
        state: disabled
      when: ansible_facts['os_family'] == "Debian"

    - name: Disable firewall rules (Redhat)
      service:
        name: firewalld
        state: stopped
      when: ansible_facts['os_family'] == "RedHat"

    - name: install jq for daemon json parsing on all machines
      package:
        name:
        - jq

    - name: Validate nvidia dns is resolvable on all hosts
      shell: 'curl https://nvidia.github.io/nvidia-docker/gpgkey'

    - name: Validate nvidia dns is resolvable on all hosts
      shell: 'curl https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub'

    - name: Install python dependencies
      include_role:
        name: mrlesmithjr.ansible_bootstrap_python

    - name: Install the Docker daemon
      include_role:
        name: mrlesmithjr.docker
      vars:
        docker_config_users: true
        docker_users:
        - "vagrant"

    - name: Copy daemon.json with logging, gpu, and various other settings to all hosts
      copy:
        src: daemon.json
        dest: /etc/docker/daemon.json

    - name: Restart service docker to process new daemon.json
      service:
        name: docker
        state: restarted

    - name: Install cuda drivers
      include_role:
        name: nvidia.nvidia_driver
      vars:
        nvidia_driver_ubuntu_install_from_cuda_repo: yes

    - name: Install Nvidia Docker
      include_role:
        name: nvidia.nvidia_docker

    - name: find how many gpus are registered with the nvidia driver
      shell: "nvidia-smi -L | grep UUID | wc -l"
      register: gpu_count

    - name: Append generic resources to daemon json
      become: true
      shell: 'cat /etc/docker/daemon.json | jq ". |= . + {\"node-generic-resources\": [\"pienso-gpu={{ gpu_count.stdout | int }}\"]}"'
      register: json

    - name: write new daemon json
      copy:
        content: "{{ json.stdout }}"
        dest: "/etc/docker/daemon.json"

    - name: Restart service docker, in all cases, for changes to take effect
      service:
        name: docker
        state: restarted

    - name: Configure the Docker daemon
      include_role:
        name: mrlesmithjr.ansible-docker-swarm
      vars:
        docker_swarm_interface: "eth1"



