#
# Vagrant.configure("2") do |config|
#   # Every Vagrant development environment requires a box. You can search for
#   # boxes at https://vagrantcloud.com/search.
#   config.vm.box = "generic/ubuntu1804"
#
#   # Disable automatic box update checking. If you disable this, then
#   # boxes will only be checked for updates when the user runs
#   # `vagrant box outdated`. This is not recommended.
#   config.vm.box_check_update = false
#
#   # Create a forwarded port mapping which allows access to a specific port
#   # within the machine from a port on the host machine. In the example below,
#   # accessing "localhost:8080" will access port 80 on the guest machine.
#   # NOTE: This will enable public access to the opened port
#   config.vm.network "forwarded_port", guest: 22, host: 4567
#
#   #
#    config.vm.provider "virtualbox" do |vb|
#      # Display the VirtualBox GUI when booting the machine
#      vb.gui = true
#
#      # Customize the amount of memory on the VM:
#      vb.memory = "1024"
#    end
# end

servers=[
  {
    :hostname => "uno",
    :ip => "10.10.1.125",
    :box => "generic/ubuntu1804",
    :ram => 1024,
  },
  {
    :hostname => "dos",
    :ip => "10.10.1.126",
    :box => "generic/ubuntu1804",
    :ram => 1024,
  },
  {
    :hostname => "tres",
    :ip => "10.10.1.127",
    :box => "generic/ubuntu1804",
    :ram => 1024,
  },
 {
   :hostname => "quatro",
   :ip => "10.10.1.128",
   :box => "centos/7",
   :ram => 1024,
 }
]

Vagrant.configure("2") do |config|
config.ssh.forward_agent = true
    config.vm.provision "shell" do |s|
        ssh_pub_key = File.readlines("/Users/jmurphy/.ssh/id_rsa.pub").first.strip
        s.inline = <<-SHELL
#         apt-get update
        echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
        SHELL
    end
    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.hostname = machine[:hostname]
            node.vm.network "private_network", ip: machine[:ip]
            node.vm.provider "virtualbox" do |vb|
                vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
                vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
                vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
            end
        end
    end
end
